linters:
  disable:
    - errcheck        # Отключает проверку возвратных значений ошибок (errcheck).
  enable:
    - govet           # Анализирует код на предмет потенциальных ошибок и проблем.
    - gofmt           # Проверяет форматирование кода согласно стандарту gofmt.
    - revive          # Современная альтернатива golint, проверяет стиль и читаемость кода.
    - staticcheck     # Проводит статический анализ кода, выявляет ошибки, проблемы производительности и т.д.
    - unused          # Проверяет неиспользуемые переменные, функции, типы и т.д.
run:
  deadline: 2m
issues:
  exclude-use-default: false
